apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: nrp
  labels:
    app: postgres
spec:
  containers:
  - name: postgres-container
    image: postgres:latest
    env:
    - name: POSTGRES_USER
      value: "admin"
    - name: POSTGRES_PASSWORD
      value: "password"
    - name: POSTGRES_DB
      value: "nrp_db"
    ports:
    - containerPort: 5432
